name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
      - name: Deploy to IIS Folder (MySite)
        run: |
          $source = "D:\a\simple-html-devops\simple-html-devops"
          $destination = "D:\IIS Sites\MySite"
          if (Test-Path $destination) {
              Remove-Item $destination -Recurse -Force
          }
          New-Item -ItemType Directory -Force -Path $destination
          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
