name: 🚀 Deploy Simple HTML Website to IIS

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: windows-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Files
        run: |
          Write-Host "Listing repository files..."
          Get-ChildItem -Recurse
      - name: Deploy to IIS (MySite)
        shell: pwsh
        run: |
          $source = "D:\a\simple-html-devops\simple-html-devops"
          $destination = "D:\IIS Sites\MySite"
          Write-Host "Starting deployment to IIS MySite folder..."

          if (Test-Path $destination) {
              Remove-Item $destination -Recurse -Force
              Write-Host "Old site deleted."
          }
          New-Item -ItemType Directory -Force -Path $destination | Out-Null
          Write-Host "New site folder created."
          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
          Write-Host "Files successfully copied to IIS site."
      - name: Confirm Deployment
        run: |
          Write-Host "✅ Deployment completed successfully to IIS!"
          Write-Host "Visit your site at: http://localhost or your server IP"
