name: Build & Deploy to IIS (MySite)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on:  windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run build (minify + prepare build folder)
        run: npm run build

      - name: Deploy to IIS (MySite)
        shell: pwsh
        run: |
          $source = "${{ github.workspace }}\build"
          $destination = "D:\IIS Sites\MySite"

          Write-Host "Deploying build -> $destination"

          if (Test-Path $destination) {
            Remove-Item $destination -Recurse -Force
          }
          New-Item -ItemType Directory -Path $destination | Out-Null
          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force

      - name: Restart website
        shell: pwsh
        run: |
          Import-Module WebAdministration
          Stop-Website -Name "MySite" -ErrorAction SilentlyContinue
          Start-Website -Name "MySite"
