name: Deploy Static HTML Site to IIS (MySite)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy HTML files to IIS
        shell: pwsh
        run: |
          $source = "${{ github.workspace }}"
          $destination = D:\IIS Sites\MySite

          Write-Host "Deploying files to IIS: $destination"

          if (Test-Path $destination) {
            Remove-Item $destination -Recurse -Force
          }

          New-Item -ItemType Directory -Path $destination | Out-Null
          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force

      - name: Restart IIS Website
        shell: pwsh
        run: |
          Import-Module WebAdministration
          Stop-Website -Name "Mysite" -ErrorAction SilentlyContinue
          Start-Website -Name "Mysite"
